name = "MPSExperiments"
uuid = "298b07f2-4fec-42fe-b83d-9e02fb6e41bf"
authors = ["Stefano Crotti <stefano.crotti@polito.it> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "0.0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
